# Generated by Django 2.0.7 on 2018-07-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echosign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturetype',
            name='access_token',
            field=models.CharField(default='', help_text='https://www.adobe.io/apis/documentcloud/sign/docs/overview.html', max_length=100, verbose_name='Echosign token'),
        ),
        migrations.AddField(
            model_name='signaturetype',
            name='application_id',
            field=models.CharField(default='', help_text='https://www.adobe.io/apis/documentcloud/sign/docs/overview.html', max_length=100, verbose_name='Echosign application id'),
        ),
        migrations.AddField(
            model_name='signaturetype',
            name='application_secret',
            field=models.CharField(default='', help_text='https://www.adobe.io/apis/documentcloud/sign/docs/overview.html', max_length=100, verbose_name='Echosign application secret'),
        ),
    ]
