# Generated by Django 2.0.7 on 2018-07-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echosign', '0003_auto_20180711_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='state',
            field=models.CharField(default='IN_PROCESS', help_text='https://secure.na1.echosign.com/public/docs/restapi/v6#ParticipantSetInfopost_agreements', max_length=100, verbose_name='Echosign state'),
        ),
        migrations.AlterField(
            model_name='signaturetype',
            name='root_url',
            field=models.CharField(default='https://secure.eu1.echosign.com', max_length=255, verbose_name='Echosign root url'),
        ),
    ]
