# Generated by Django 2.0.7 on 2018-07-10 14:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_backend_id', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='ID for signature backend')),
                ('anysign_internal_id', models.UUIDField(default=uuid.uuid4, verbose_name='ID in internal database')),
                ('document', models.FileField(upload_to='signatures', verbose_name='document')),
                ('document_title', models.CharField(max_length=100, verbose_name='title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignatureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_backend_code', models.CharField(db_index=True, max_length=50, verbose_name='signature backend')),
                ('root_url', models.URLField(default='http://foo', max_length=255, verbose_name='Echosign root url')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Signer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signing_order', models.PositiveSmallIntegerField(default=0, help_text='Position in the list of signers.', verbose_name='signing order')),
                ('signature_backend_id', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='ID in signature backend')),
                ('anysign_internal_id', models.UUIDField(default=uuid.uuid4, verbose_name='ID in internal database')),
                ('full_name', models.CharField(db_index=True, max_length=50, verbose_name='full name')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email')),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='echosign.Signature')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='signature',
            name='signature_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echosign.SignatureType', verbose_name='signature type'),
        ),
    ]
