# Generated by Django 2.0.7 on 2018-07-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echosign', '0002_auto_20180710_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturetype',
            name='root_url',
            field=models.CharField(default='http://foo', max_length=255, verbose_name='Echosign root url'),
        ),
    ]
